<!--Kurs.com.ua mini 112x60 comm usd/uah/eur/uah orange-->
<div id='kurs-com-ua-informer-mini-112x60-comm-usd-uah-eur-uah-orange-container'><a href="//old.kurs.com.ua/informer" id="kurs-com-ua-informer-mini-112x60-comm-usd-uah-eur-uah-blue" title="Курс валют информер Украина" rel="nofollow" target="_blank">Информер курса валют</a></div>
<script type='text/javascript'>
(function() {var iframe = '<ifr'+'ame src="//old.kurs.com.ua/informer/mini2/comm/usd/uah/eur/uah?color=orange" width="112" height="60" frameborder="0" vspace="0" scrolling="no" hspace="0"></ifr'+'ame>';var container = document.getElementById('kurs-com-ua-informer-mini-112x60-comm-usd-uah-eur-uah-blue');container.parentNode.innerHTML = iframe;})();
</script>
<noscript><img src='//old.kurs.com.ua/static/images/informer/kurs.png' width='52' height='26' alt='old.kurs.com.ua: курс валют в Украине!' title='Курс валют' border='0' /></noscript>
<!--//Kurs.com.ua mini 112x60 comm usd/uah/eur/uah orange-->

<!--bigmir)net TOP 100-->
<script type="text/javascript" language="javascript">
function BM_Draw(oBM_STAT){
document.write('<table cellpadding="0" cellspacing="0" border="0" style="display:inline;margin-right:4px;"><tr><td><div style="margin:0px;padding:0px;font-size:1px;width:88px;"><div style="background:url(\'//i.bigmir.net/cnt/samples/diagonal/b61_top.gif\') no-repeat bottom;"> </div><div style="font:10px Tahoma;background:url(\'//i.bigmir.net/cnt/samples/diagonal/b61_center.gif\');"><div style="text-align:center;"><a href="http://www.bigmir.net/" target="_blank" style="color:#0000ab;text-decoration:none;font:10px Tahoma;">bigmir<span style="color:#ff0000;">)</span>net</a></div><div style="margin-top:3px;padding: 0px 6px 0px 6px;color:#e2762d;"><div style="float:left;font:10px Tahoma;">'+oBM_STAT.hosts+'</div><div style="float:right;font:10px Tahoma;">'+oBM_STAT.hits+'</div></div><br clear="all"/></div><div style="background:url(\'//i.bigmir.net/cnt/samples/diagonal/b61_bottom.gif\') no-repeat top;"> </div></div></td></tr></table>');
}
</script>
<script type="text/javascript" language="javascript">
bmN=navigator,bmD=document,bmD.cookie='b=b',i=0,bs=[],bm={o:1,v:16796616,s:16796616,t:0,c:bmD.cookie?1:0,n:Math.round((Math.random()* 1000000)),w:0};
for(var f=self;f!=f.parent;f=f.parent)bm.w++;
try{if(bmN.plugins&&bmN.mimeTypes.length&&(x=bmN.plugins['Shockwave Flash']))bm.m=parseInt(x.description.replace(/([a-zA-Z]|\s)+/,''));
else for(var f=3;f<20;f++)if(eval('new ActiveXObject("ShockwaveFlash.ShockwaveFlash.'+f+'")'))bm.m=f}catch(e){;}
try{bm.y=bmN.javaEnabled()?1:0}catch(e){;}
try{bmS=screen;bm.v^=bm.d=bmS.colorDepth||bmS.pixelDepth;bm.v^=bm.r=bmS.width}catch(e){;}
r=bmD.referrer.replace(/^w+:\/\//,'');if(r&&r.split('/')[0]!=window.location.host){bm.f=escape(r).slice(0,400);bm.v^=r.length}
bm.v^=window.location.href.length;for(var x in bm) if(/^[ovstcnwmydrf]$/.test(x)) bs[i++]=x+bm[x];
bmD.write('<sc'+'ript type="text/javascript" language="javascript" src="//c.bigmir.net/?'+bs.join('&')+'"></sc'+'ript>');
</script>
<noscript>
<a href="http://www.bigmir.net/" target="_blank"><img src="//c.bigmir.net/?v16796616&s16796616&t2" width="88" height="31" alt="bigmir)net TOP 100" title="bigmir)net TOP 100" border="0" /></a>
</noscript>
<!--bigmir)net TOP 100-->