

<!--Kurs.com.ua mini 112x60 nbu usd/uah/eur/uah orange-->
<div id='kurs-com-ua-informer-mini-112x60-nbu-usd-uah-eur-uah-orange-container'><a href="//old.kurs.com.ua/informer" id="kurs-com-ua-informer-mini-112x60-nbu-usd-uah-eur-uah-orange" title="Курс валют информер Украина" rel="nofollow" target="_blank">Информер курса валют</a></div>
<script type='text/javascript'>
(function() {var iframe = '<ifr'+'ame src="//old.kurs.com.ua/informer/mini2/nbu/usd/uah/eur/uah?color=orange" width="112" height="60" frameborder="0" vspace="0" scrolling="no" hspace="0"></ifr'+'ame>';var container = document.getElementById('kurs-com-ua-informer-mini-112x60-nbu-usd-uah-eur-uah-orange');container.parentNode.innerHTML = iframe;})();
</script>
<noscript><img src='//old.kurs.com.ua/static/images/informer/kurs.png' width='52' height='26' alt='old.kurs.com.ua: курс валют в Украине!' title='Курс валют' border='0' /></noscript>
<!--//Kurs.com.ua mini 112x60 nbu usd/uah/eur/uah orange-->
